#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
git lfs pre-push "$@"

yarn run lint:code

if [ $? -ne 0 ]; then
  exit 1
fi

yarn run lint:format

if [ $? -ne 0 ]; then
  exit 1
fi

yarn run lint:commits

if [ $? -ne 0 ]; then
  exit 1
fi

yarn run build

if [ $? -ne 0 ]; then
  exit 1
fi

yarn run test:ci
